export const Coffee = [
  {
    id: 1,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 2,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 3,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 4,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 5,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 6,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 7,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 8,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 9,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 10,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 11,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 12,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 14,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
  {
    id: 15,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
  },
]
