export const Coffee = [
  {
    id: 1,
    nome: 'Expresso Tradicional',
    preco: '9,90',
    descricao: 'O tradicional café feito com água quente e grãos moídos',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 2,
    nome: 'Expresso Americano',
    preco: '9,90',
    descricao: 'Expresso diluído, menos intenso que o tradicional',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 3,
    nome: 'Expresso Cremoso',
    preco: '9,90',
    descricao: 'Café expresso tradicional com espuma cremosa',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 4,
    nome: 'Expresso Gelado',
    preco: '9,90',
    descricao: 'Bebida preparada com café expresso e cubos de gelo',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 5,
    nome: 'Café com Leite',
    preco: '9,90',
    descricao: 'Meio a meio de expresso tradicional com leite vaporizado',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 6,
    nome: 'Latte',
    preco: '9,90',
    descricao:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 7,
    nome: 'Capuccino',
    preco: '9,90',
    descricao:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 8,
    nome: 'Macchiato',
    preco: '9,90',
    descricao: 'Café expresso misturado com um pouco de leite quente e espuma',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 9,
    nome: 'Mocaccino',
    preco: '9,90',
    descricao: 'Café expresso com calda de chocolate, pouco leite e espuma',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 10,
    nome: 'Chocolate Quente',
    preco: '9,90',
    descricao: 'Bebida feita com chocolate dissolvido no leite quente e café',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 11,
    nome: 'Cubano',
    preco: '9,90',
    descricao:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 12,
    nome: 'Havaiano',
    preco: '9,90',
    descricao: 'Bebida adocicada preparada com café e leite de coco',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 13,
    nome: 'Árabe',
    preco: '9,90',
    descricao: 'Bebida preparada com grãos de café árabe e especiarias',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
  {
    id: 14,
    nome: 'Irlandês',
    preco: '9,90',
    descricao: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    image: 'https://i.imgur.com/GoGTcuT.png',
    tag: {
      tradicional: true,
      gelado: false,
      comLeite: false,
      especial: false,
      alcoolico: false,
    },
  },
]
